// ─── Styles (shared across all Sidebar sub-components) ────────────────────────

const styles = {
  sidebar: {
    minWidth: 180,
    maxWidth: 'min(420px, 30vw)',
    background: '#0b0b0b',
    borderRight: '1px solid #161616',
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    userSelect: 'none',
    flexShrink: 0,
    position: 'relative',
  },
  resizer: {
    position: 'absolute',
    top: 0,
    right: -3,
    bottom: 0,
    width: 6,
    cursor: 'col-resize',
    zIndex: 100,
    background: 'transparent',
    transition: 'background 0.15s',
  },

  // Header with macOS traffic-light space
  // Drag region is set via `.drag-region` className (see global CSS in index.js)
  header: {
    padding: '14px 16px 14px',
    paddingTop: 42,
    borderBottom: '1px solid #141414',
  },
  headerLogo: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  logoMark: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    filter: 'drop-shadow(0 2px 8px rgba(245, 158, 11, 0.25))',
  },
  logoTextGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    minWidth: 0,
  },
  logoTextRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  logoText: {
    fontSize: 18,
    fontWeight: 700,
    color: '#fafafa',
    fontFamily: '"PingFang SC", "Inter", "SF Pro Display", system-ui',
    letterSpacing: '0.04em',
    lineHeight: 1,
    background: 'linear-gradient(135deg, #fde68a 0%, #fbbf24 50%, #f59e0b 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  logoBadge: {
    fontSize: 8,
    fontWeight: 700,
    fontFamily: '"JetBrains Mono", monospace',
    color: '#f59e0b',
    background: 'rgba(245, 158, 11, 0.1)',
    border: '1px solid rgba(245, 158, 11, 0.28)',
    borderRadius: 3,
    padding: '2px 5px',
    letterSpacing: '0.1em',
    lineHeight: 1,
  },
  logoSubText: {
    fontSize: 9,
    fontWeight: 500,
    color: '#3a3a3a',
    fontFamily: '"Inter", system-ui',
    lineHeight: 1.2,
    letterSpacing: '0.04em',
  },

  // Stats strip
  statsStrip: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    padding: '10px 12px',
    background: '#0a0a0a',
    borderBottom: '1px solid #141414',
  },
  statItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
  },
  statValue: {
    fontSize: 13,
    fontWeight: 600,
    color: '#d1d5db',
    fontFamily: '"JetBrains Mono", monospace',
    lineHeight: 1.2,
  },
  statLabel: {
    fontSize: 9,
    color: '#3a3a3a',
    fontFamily: 'system-ui',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  statDivider: {
    width: 1,
    height: 20,
    background: '#161616',
  },

  // Section header
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 14px 8px',
  },
  sectionLabel: {
    fontSize: 10,
    color: '#333',
    fontFamily: 'system-ui',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    fontWeight: 600,
  },
  addProjectBtn: {
    background: '#151515',
    border: '1px solid #232323',
    borderRadius: 4,
    color: '#888',
    cursor: 'pointer',
    padding: '3px 5px',
    display: 'flex',
    alignItems: 'center',
    outline: 'none',
    transition: 'all 0.15s',
  },
  templateMenu: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    right: 0,
    width: 260,
    background: '#0d0d0d',
    border: '1px solid #1e1e1e',
    borderRadius: 8,
    boxShadow: '0 12px 32px rgba(0,0,0,0.6), 0 2px 6px rgba(0,0,0,0.4)',
    padding: 6,
    zIndex: 100,
    animation: 'toast-in 0.18s ease',
  },
  menuHeader: {
    fontSize: 9,
    color: '#3a3a3a',
    padding: '6px 10px 4px',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  templateItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 10,
    width: '100%',
    background: 'transparent',
    border: 'none',
    borderRadius: 5,
    padding: '8px 10px',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background 0.1s',
  },
  templateIcon: {
    fontSize: 14,
    color: '#f59e0b',
    marginTop: 1,
    flexShrink: 0,
  },
  templateInfo: { flex: 1, minWidth: 0 },
  templateName: {
    fontSize: 12,
    fontWeight: 600,
    color: '#d0d0d0',
    fontFamily: 'var(--font-ui)',
    marginBottom: 2,
  },
  templateDesc: {
    fontSize: 10,
    color: '#555',
    fontFamily: 'var(--font-ui)',
    lineHeight: 1.4,
  },

  // Projects list
  projectsList: {
    flex: 1,
    overflowY: 'auto',
    overflowX: 'hidden',
    padding: '0 0 8px',
  },
  // Drag-over highlight when dragging a folder from Finder onto the projects list
  projectsListDragOver: {
    boxShadow: 'inset 0 0 0 2px rgba(245, 158, 11, 0.55)',
    background: 'rgba(245, 158, 11, 0.03)',
  },
  projectSection: {
    marginBottom: 3,
  },
  projectHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 10px 6px 10px',
    cursor: 'pointer',
    borderRadius: 5,
    margin: '0 6px',
    transition: 'background 0.1s',
  },
  chevron: {
    color: '#383838',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    width: 9,
  },
  folderIcon: {
    color: '#f59e0b',
    flexShrink: 0,
    display: 'flex',
  },
  projectName: {
    fontSize: 12,
    fontWeight: 600,
    color: '#c8ccd1',
    fontFamily: 'system-ui',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    letterSpacing: '-0.005em',
  },
  projectPath: {
    fontSize: 10,
    color: '#2a2a2a',
    fontFamily: '"JetBrains Mono", monospace',
    padding: '0 10px 4px 32px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  projectActions: {
    display: 'flex',
    gap: 1,
    alignItems: 'center',
  },

  // Session rows
  sessionRow: {
    position: 'relative',
    display: 'flex',
    cursor: 'pointer',
    borderRadius: 4,
    margin: '1px 6px',
    transition: 'background 0.1s',
    padding: '5px 10px 5px 30px',
  },
  sessionMainRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    width: '100%',
  },
  sessionActions: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    flexShrink: 0,
  },
  renameInput: {
    flex: 1,
    background: '#1a1a1a',
    border: '1px solid #f59e0b',
    borderRadius: 3,
    color: '#e2e8f0',
    fontSize: 12,
    fontFamily: 'var(--font-ui)',
    padding: '2px 6px',
    outline: 'none',
    minWidth: 0,
  },
  sessionSubLine: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    fontSize: 10,
    fontFamily: 'var(--font-mono)',
    fontVariantNumeric: 'tabular-nums',
    paddingLeft: 18,
    paddingTop: 2,
    paddingBottom: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  subLineDim: {
    color: '#444',
    fontWeight: 500,
  },
  subLineMuted: {
    color: '#3a3a3a',
    fontWeight: 500,
  },
  sessionRowHover: {
    background: '#131313',
  },
  sessionRowActive: {
    background: 'linear-gradient(to right, rgba(245, 158, 11, 0.08), transparent)',
  },
  activeBar: {
    position: 'absolute',
    left: 6,
    top: 6,
    bottom: 6,
    width: 2,
    borderRadius: 2,
    background: '#f59e0b',
    transition: 'opacity 0.15s',
  },
  sessionIcon: {
    display: 'flex',
    flexShrink: 0,
    transition: 'color 0.15s',
  },
  sessionName: {
    fontSize: 12,
    fontFamily: 'system-ui',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    transition: 'all 0.15s',
  },
  iconBtn: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: '3px 4px',
    display: 'flex',
    alignItems: 'center',
    borderRadius: 3,
    outline: 'none',
    transition: 'color 0.15s',
  },

  // Running-status pulsing dot shown on the right side of a session row
  // when an AI tool is active in that session.
  runningPulse: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    animation: 'pulse 1.8s ease-in-out infinite',
    flexShrink: 0,
    marginRight: 2,
  },

  // Inline edit input
  inlineInput: {
    background: '#1a1a1a',
    border: '1px solid #3a3a3a',
    borderRadius: 3,
    color: '#e2e8f0',
    fontSize: 12,
    fontFamily: 'system-ui',
    padding: '2px 5px',
    outline: 'none',
    flex: 1,
    minWidth: 0,
  },

  // Empty state
  emptyHint: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '40px 16px',
    gap: 8,
  },
  emptyIcon: {
    fontSize: 28,
    color: '#1e1e1e',
    marginBottom: 4,
  },
  emptyText: {
    fontSize: 11,
    color: '#444',
    fontFamily: 'system-ui',
  },
  emptySubText: {
    fontSize: 10,
    color: '#2a2a2a',
    fontFamily: 'system-ui',
    textAlign: 'center',
    lineHeight: 1.5,
  },

  // Footer
  footer: {
    padding: '8px 14px 12px',
    borderTop: '1px solid #121212',
  },
  footerText: {
    fontSize: 9,
    color: '#262626',
    fontFamily: 'system-ui',
    letterSpacing: '0.02em',
  },

  // Group section (contains group header + project sections)
  groupSection: {
    marginBottom: 2,
  },
  groupHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '6px 10px 5px 8px',
    cursor: 'pointer',
    borderRadius: 5,
    margin: '0 6px',
    transition: 'background 0.1s',
    userSelect: 'none',
  },
  groupName: {
    fontSize: 11,
    fontWeight: 600,
    color: '#888',
    fontFamily: 'system-ui',
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    letterSpacing: '0.02em',
  },
  groupCount: {
    fontSize: 10,
    color: '#333',
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 500,
    flexShrink: 0,
  },
  groupRenameInput: {
    flex: 1,
    background: '#1a1a1a',
    border: '1px solid #f59e0b',
    borderRadius: 3,
    color: '#e2e8f0',
    fontSize: 11,
    fontFamily: 'system-ui',
    padding: '1px 5px',
    outline: 'none',
    minWidth: 0,
  },
};

export default styles;
