/**
 * Shared styles for SettingsModal sub-components.
 * All sub-components import from this single file to avoid duplication.
 */

const styles = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0, 0, 0, 0.65)',
    backdropFilter: 'blur(6px)',
    WebkitBackdropFilter: 'blur(6px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9998,
    animation: 'fade-in 0.18s ease',
  },
  modal: {
    width: 680,
    maxHeight: '82vh',
    background: '#0d0d0d',
    border: '1px solid #1e1e1e',
    borderRadius: 10,
    boxShadow: '0 20px 60px rgba(0,0,0,0.7), 0 4px 12px rgba(0,0,0,0.5)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    animation: 'toast-in 0.22s cubic-bezier(0.16, 1, 0.3, 1)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 20px',
    borderBottom: '1px solid #1a1a1a',
    background: '#0f0f0f',
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 10 },
  headerIcon: { fontSize: 16, color: '#f59e0b' },
  headerTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#e2e8f0',
    fontFamily: '"SF Pro Display", system-ui',
    letterSpacing: '-0.01em',
  },
  closeBtn: {
    background: 'transparent',
    border: 'none',
    color: '#555',
    fontSize: 22,
    cursor: 'pointer',
    width: 26,
    height: 26,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    lineHeight: 1,
    padding: 0,
  },
  tabs: {
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    padding: '0 16px',
    borderBottom: '1px solid #161616',
    background: '#0b0b0b',
  },
  tab: {
    background: 'transparent',
    border: 'none',
    borderBottom: '2px solid transparent',
    padding: '11px 12px 10px',
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'system-ui',
    transition: 'all 0.15s',
  },
  refreshBtn: {
    background: '#151515',
    border: '1px solid #242424',
    borderRadius: 5,
    color: '#888',
    padding: '4px 10px',
    fontSize: 11,
    cursor: 'pointer',
    fontFamily: 'system-ui',
  },
  body: {
    flex: 1,
    overflowY: 'auto',
    padding: '16px 20px 22px',
  },

  // Tools list
  toolsList: { display: 'flex', flexDirection: 'column', gap: 10 },
  toolRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 14px',
    background: '#111',
    border: '1px solid #1a1a1a',
    borderRadius: 7,
  },
  toolBadge: {
    width: 34,
    height: 34,
    borderRadius: 6,
    border: '1px solid',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 15,
    fontWeight: 700,
    fontFamily: '"SF Pro Display", system-ui',
    flexShrink: 0,
  },
  toolInfo: { flex: 1, minWidth: 0 },
  toolName: {
    fontSize: 13,
    fontWeight: 600,
    color: '#e2e8f0',
    marginBottom: 3,
    fontFamily: 'system-ui',
  },
  toolMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    fontSize: 11,
  },
  toolCmd: {
    color: '#666',
    background: '#0a0a0a',
    padding: '2px 6px',
    borderRadius: 3,
    fontFamily: '"JetBrains Mono", monospace',
  },
  toolBadgeSmall: {
    fontSize: 10,
    fontFamily: '"JetBrains Mono", monospace',
    fontWeight: 500,
  },
  toolActions: { flexShrink: 0 },
  btnPrimary: {
    background: 'transparent',
    border: '1px solid',
    borderRadius: 5,
    padding: '5px 14px',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'system-ui',
    transition: 'all 0.15s',
  },
  btnSecondary: {
    background: '#151515',
    border: '1px solid #262626',
    borderRadius: 5,
    padding: '5px 14px',
    fontSize: 11,
    color: '#888',
    cursor: 'pointer',
    fontFamily: 'system-ui',
  },

  // Providers
  providersList: { display: 'flex', flexDirection: 'column', gap: 14 },
  hint: {
    fontSize: 11,
    color: '#555',
    marginBottom: 4,
    lineHeight: 1.6,
    fontFamily: 'system-ui',
  },
  providerCard: {
    background: '#111',
    border: '1px solid #1a1a1a',
    borderLeftWidth: 3,
    borderRadius: 7,
    padding: '14px 16px',
  },
  providerHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  providerTitle: { flex: 1 },
  providerName: {
    fontSize: 13,
    fontWeight: 600,
    color: '#e2e8f0',
    marginBottom: 2,
    fontFamily: 'system-ui',
  },
  providerSub: {
    fontSize: 10,
    color: '#555',
    fontFamily: 'system-ui',
  },
  providerForm: { display: 'flex', flexDirection: 'column', gap: 9 },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  fieldLabel: {
    fontSize: 10,
    color: '#4a4a4a',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    fontFamily: 'system-ui',
  },
  input: {
    background: '#0a0a0a',
    border: '1px solid #1e1e1e',
    borderRadius: 4,
    color: '#e2e8f0',
    padding: '6px 10px',
    fontSize: 12,
    fontFamily: '"JetBrains Mono", monospace',
    outline: 'none',
    width: '100%',
  },
  keyRow: { display: 'flex', gap: 6 },
  smallBtn: {
    background: '#151515',
    border: '1px solid #242424',
    borderRadius: 4,
    color: '#777',
    padding: '4px 9px',
    fontSize: 10,
    cursor: 'pointer',
    fontFamily: 'system-ui',
    flexShrink: 0,
  },
  modelRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: 8,
  },

  codeMark: {
    color: '#f59e0b',
    background: 'rgba(245, 158, 11, 0.08)',
    padding: '1px 5px',
    borderRadius: 3,
    fontFamily: 'var(--font-mono)',
    fontSize: 11,
  },

  // Agent config tab
  agentList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginTop: 6,
  },
  agentRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: '11px 14px',
    background: '#111',
    border: '1px solid #1a1a1a',
    borderRadius: 6,
  },
  agentRowLeft: {
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    minWidth: 0,
  },
  agentRowRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 7,
    flexShrink: 0,
  },
  agentName: {
    fontSize: 12,
    fontWeight: 600,
    color: '#d0d0d0',
    fontFamily: 'var(--font-ui)',
  },
  agentPath: {
    fontSize: 10,
    color: '#666',
    fontFamily: 'var(--font-mono)',
    background: '#0a0a0a',
    padding: '1px 6px',
    borderRadius: 3,
    border: '1px solid #1a1a1a',
    width: 'fit-content',
  },
  agentDim: {
    fontSize: 10,
    color: '#3a3a3a',
    fontFamily: 'var(--font-mono)',
  },
  agentExists: {
    fontSize: 10,
    color: '#22c55e',
    fontFamily: 'var(--font-mono)',
    fontWeight: 600,
  },
  btnSmall: {
    background: '#1a150a',
    border: '1px solid #3a2e0a',
    borderRadius: 4,
    color: '#f59e0b',
    fontSize: 10,
    padding: '4px 10px',
    cursor: 'pointer',
    fontFamily: 'var(--font-ui)',
    fontWeight: 600,
  },
  btnSmallSec: {
    background: '#151515',
    border: '1px solid #242424',
    borderRadius: 4,
    color: '#777',
    fontSize: 10,
    padding: '4px 10px',
    cursor: 'pointer',
    fontFamily: 'var(--font-ui)',
  },

  // Appearance tab
  themeRow: {
    display: 'flex',
    gap: 14,
    marginTop: 10,
  },
  themeCard: {
    flex: 1,
    background: '#0d0d0d',
    border: '1px solid #1e1e1e',
    borderRadius: 8,
    padding: 14,
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
  },
  themePreview: {
    display: 'flex',
    width: '100%',
    height: 70,
    borderRadius: 5,
    overflow: 'hidden',
    border: '1px solid #1a1a1a',
  },
  themePreviewSidebar: {
    width: '32%',
    borderRight: '1px solid rgba(255,255,255,0.05)',
  },
  themePreviewMain: {
    flex: 1,
    padding: 6,
  },
  themePreviewBar: {
    width: '40%',
    height: 4,
    borderRadius: 2,
  },
  themeLabel: {
    fontSize: 12,
    fontWeight: 500,
    fontFamily: 'var(--font-ui)',
  },
  wipBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    fontSize: 9,
    fontWeight: 700,
    color: '#eab308',
    background: 'rgba(234, 179, 8, 0.12)',
    border: '1px solid rgba(234, 179, 8, 0.3)',
    borderRadius: 3,
    padding: '2px 6px',
    fontFamily: 'var(--font-mono)',
    letterSpacing: '0.05em',
  },
  hintDim: {
    fontSize: 10,
    color: '#3a3a3a',
    marginTop: 14,
    lineHeight: 1.6,
    fontFamily: 'var(--font-ui)',
  },

  // Toggle row (label + description + switch)
  toggleRow: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    padding: '4px 0',
  },
  toggleInfo: {
    flex: 1,
  },
  toggleLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: '#e2e8f0',
    fontFamily: 'var(--font-ui)',
    marginBottom: 4,
  },
  toggleDesc: {
    fontSize: 11,
    color: '#666',
    lineHeight: 1.55,
    fontFamily: 'var(--font-ui)',
  },
  switch: {
    width: 38,
    height: 22,
    border: '1px solid #2a2a2a',
    borderRadius: 11,
    cursor: 'pointer',
    padding: '2px',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    transition: 'all 0.2s',
    marginTop: 2,
  },
  switchKnob: {
    width: 16,
    height: 16,
    borderRadius: '50%',
    transition: 'transform 0.18s, background 0.18s',
  },

  // About
  aboutBox: {
    padding: '10px 4px',
  },
  aboutTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#e2e8f0',
    marginBottom: 10,
    fontFamily: '"SF Pro Display", system-ui',
  },
  aboutText: {
    fontSize: 12,
    color: '#888',
    lineHeight: 1.7,
    marginBottom: 6,
    fontFamily: 'system-ui',
  },
  aboutMeta: {
    marginTop: 16,
    fontSize: 10,
    color: '#3a3a3a',
    fontFamily: '"JetBrains Mono", monospace',
    lineHeight: 1.8,
  },
};

export default styles;
